-- insert into USERS (name, password) values ('Johann Bandion', 'password');

insert into UserEntity (userName, password) values ('Johann Bandion', 'password');
insert into UserEntity (userName, password) values ('Tobias Jamnik', 'password');
insert into UserEntity (userName, password) values ('Tobias Bandion', 'password');
insert into UserEntity (userName, password) values ('Johann Jamnik', 'password');
insert into UserEntity (userName, password) values ('Lendard Bandion', 'password');
insert into UserEntity (userName, password) values ('Johann Okron', 'password');
insert into UserEntity (userName, password) values ('Lenard Okorn', 'password');
insert into UserEntity (userName, password) values ('Lenard Jamnik', 'password');
insert into UserEntity (userName, password) values ('Tobias Okorn', 'password');
insert into UserEntity (userName, password) values ('Moritz Moritz', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('John Smith', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('Emma Johnson', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('Michael Brown', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('Sophia Davis', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('William Miller', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('Olivia Wilson', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('James Anderson', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('Ava Taylor', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('Benjamin Martinez', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('Isabella Thompson', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('Daniel Lewis', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('Mia Clark', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('Joseph Rodriguez', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('Charlotte Lee', 'password');
INSERT INTO UserEntity (userName, password) VALUES ('Henry Hernandez', 'password');
